#!/bin/sh

sudo echo ""

git checkout .
git pull

composer install --optimize-autoloader

./console doctrine:migrations:migrate --no-interaction

sudo setfacl -R -m u:`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`:rwx -m u:`whoami`:rwx app/cache app/logs web/cache web/uploads/photos web/uploads/images web/pdw_file_browser/cache web/uploads/wysiwyg web/certificates
sudo setfacl -dR -m u:`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`:rwx -m u:`whoami`:rwx app/cache app/logs web/cache web/uploads/photos web/uploads/images web/pdw_file_browser/cache web/uploads/wysiwyg web/certificates
sudo rm -rf app/cache/* web/cache/* web/pdw_file_browser/cache/*

git checkout .

echo "Updated!"
