app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app_admin:
    resource: "@AppBundle/Resources/config/routing_admin.yml"
    prefix:   /admin/

app_training:
    resource: "@AppBundle/Resources/config/routing_training.yml"
    prefix:   /my/trainings/

payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /payments/

promo:
    resource: "@PromoBundle/Resources/config/routing.yml"
    prefix:   /promo/

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_register_resend:
    path:  /register/resend/{token}/
    defaults: { _controller: MyFOSUserBundle:Registration:resend }

fos_user_confirmation:
    path: /confirmation/{hash}/
    defaults: { _controller: MyFOSUserBundle:Registration:userConfirmation }

fos_user_confirmation_change_phone:
    path: /confirmation/change_phone/{hash}/
    defaults: { _controller: MyFOSUserBundle:Registration:userConfirmationChangePhone }

fos_user_confirmation_repeat_sms:
    path: /confirmation/repeat_sms/{hash}/
    defaults: { _controller: MyFOSUserBundle:Registration:userConfirmationRepeatSms }

fos_user_change_email:
    path: /register/change_email/{token}/
    defaults: { _controller: MyFOSUserBundle:Registration:changeEmail }

my_user_registration_check_phone_ajax:
    path: /register/check_phone_ajax/
    defaults: { _controller: MyFOSUserBundle:Registration:checkPhoneAjax }

my_user_registration_check_phone_resend_ajax:
    path: /register/check_phone_resend_ajax/
    defaults: { _controller: MyFOSUserBundle:Registration:checkPhoneResendAjax }

my_user_registration_check_phone_code_ajax:
    path: /register/check_phone_code_ajax/
    defaults: { _controller: MyFOSUserBundle:Registration:checkPhoneCodeAjax }

_imagine:
    resource: .
    type: imagine

innocead_captcha:
    resource: "@InnoceadCaptchaBundle/Resources/config/routing.yml"

article_show:
    path:  /{id}/
    defaults: { _controller: AppBundle:Default:article }
    requirements:
        id: '^[-_A-z0-9\/]+$'
