My\AppBundle\Entity\ExamLog:
    type: entity
    table: exams_logs
    repositoryClass: My\AppBundle\Repository\ExamLogRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        started_at:
            type: datetime
        ended_at:
            type: datetime
            nullable: true
        questions:
            type: array
        answers:
            type: array
        passed:
            type: boolean
    manyToOne:
        user:
            targetEntity: User
            inversedBy: exams_logs
        subject:
            targetEntity: Subject
            inversedBy: exams_logs
