My\AppBundle\Entity\Offer:
    type: entity
    table: offers
    repositoryClass: My\AppBundle\Repository\OfferRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        subtitle:
            type: string
            nullable: true
        _desc:
            type: text
            nullable: true
        description:
            type: text
            nullable: true
        started_at:
            type: date
            nullable: true
        ended_at:
            type: date
            nullable: true
        is_public:
            type: boolean
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
    oneToOne:
        image:
            targetEntity: Image
            mappedBy: offer
            cascade: [ all ]
    oneToMany:
        prices:
            targetEntity: OfferPrice
            mappedBy: offer
            cascade: [ all ]
