My\AppBundle\Entity\RegionPlace:
    type: entity
    table: regions_places
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
    oneToMany:
        users:
            targetEntity: User
            mappedBy: region_place
    manyToOne:
        region:
            targetEntity: Region
            inversedBy: places
