My\AppBundle\Entity\SliceLog:
    type: entity
    table: slices_logs
    repositoryClass: My\AppBundle\Repository\SliceLogRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        started_at:
            type: datetime
        ended_at:
            type: datetime
            nullable: true
        questions:
            type: array
        answers:
            type: array
        passed:
            type: boolean
    manyToOne:
        slice:
            targetEntity: Slice
            inversedBy: logs
        user:
            targetEntity: User
            inversedBy: slices_logs
