My\AppBundle\Entity\TestLog:
    type: entity
    table: tests_logs
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        started_at:
            type: datetime
        ended_at:
            type: datetime
            nullable: true
        questions:
            type: array
        answers:
            type: array
        passed:
            type: boolean
    manyToOne:
        user:
            targetEntity: User
            inversedBy: tests_logs
