My\AppBundle\Entity\ThemeTestLog:
    type: entity
    table: themes_tests_logs
    repositoryClass: My\AppBundle\Repository\ThemeTestLogRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        started_at:
            type: datetime
        ended_at:
            type: datetime
            nullable: true
        questions:
            type: array
        answers:
            type: array
        passed:
            type: boolean
    manyToOne:
        theme:
            targetEntity: Theme
            inversedBy: tests_logs
        user:
            targetEntity: User
            inversedBy: themes_tests_logs
