<?php

namespace My\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeTestLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeTestLogRepository extends EntityRepository
{
}
